import cohere
import os


class AIDAO:
    def __init__(self):
        self.co = cohere.ClientV2(os.getenv("COHERE_API_KEY"))

    async def generate_text(self, prompt: str,system_message = "") -> str:
        ''' prompt: message that the AI uses to generate a response. This can also be generated by the user.

        system_message: context/strict guidelines for the AI to follow, use if you're allowing the user to freely type a prompt.'''
        try:
            response = self.co.chat(
                model="command-a-03-2025", 
                messages=[
                    {"role":"system","content":system_message},
                    {"role": "user", "content": prompt}
                    ]
            )
            return response.message.content[0].text
        except Exception as e:
            raise Exception(f"Error generating AI text: {str(e)}")



# instance to call
ai_dao = AIDAO()
